# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SopdsGo < Formula
  desc "Self-hosted OPDS catalog server (Go rewrite of SOPDS)"
  homepage "https://github.com/dimgord/sopds-go"
  version "1.3.1"
  license "AGPL-3.0"

  depends_on "postgresql@16" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.1/sopds-go_1.3.1_macos_x86_64.tar.gz"
      sha256 "63f05a6722d706146656d5454a45f22d70a03e9978c00a84cdaf68db5517592f"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.1/sopds-go_1.3.1_macos_arm64.tar.gz"
      sha256 "66806b298351b5fb9a594b799cc6186937ab144bae0de9a429da2f6186828c2e"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.1/sopds-go_1.3.1_linux_x86_64.tar.gz"
      sha256 "2ab25ed615c37bec32e6b61a552345c7ac9a1b026fa142cd1ed22ad64d5b7b6c"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.1/sopds-go_1.3.1_linux_arm64.tar.gz"
      sha256 "210ed434483aca35c088cfe569e475d7851bfe817f8d67f290e99bf8e8960044"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  def caveats
    <<~EOS
      sopds-go is now installed. To complete setup:

        1. Start PostgreSQL: brew services start postgresql@16
        2. Initialize the database:
             psql -U postgres -f #{pkgshare}/init.sql
        3. Create config: sopds init
        4. Edit config.yaml.example as a starting template:
             cat #{pkgshare}/config.yaml.example
        5. Run migrations: sopds migrate
        6. Start: sopds start

      Optional runtime deps (install separately):
        - calibre        — for FB2 → MOBI conversion (`brew install calibre`)
        - espeak-ng      — for IPA-based Piper TTS voices (`brew install espeak-ng`)

      For CUDA-accelerated TTS (NVIDIA GPU only), see sopds-tts-rs/ in the
      upstream repo: https://github.com/dimgord/sopds-go/tree/main/sopds-tts-rs
    EOS
  end

  test do
    system "#{bin}/sopds", "version"
  end
end
