# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SopdsGo < Formula
  desc "Self-hosted OPDS catalog server (Go rewrite of SOPDS)"
  homepage "https://github.com/dimgord/sopds-go"
  version "1.3.2"
  license "AGPL-3.0"

  depends_on "postgresql@18" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.2/sopds-go_1.3.2_macos_x86_64.tar.gz"
      sha256 "a9bfeda6d7aa07fe83b7efc5fcc3b47a389047a82aa068b71931258022c31a4f"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.2/sopds-go_1.3.2_macos_arm64.tar.gz"
      sha256 "ebd0810520557df5961ac93a253763b2bf4efe1c5488b0fcff38b1d4b2035ce9"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.2/sopds-go_1.3.2_linux_x86_64.tar.gz"
      sha256 "e6d71ee5b25abb60557e1c02e86b7a4a2eb49335cbb8f95890737cbad1ddf1e9"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.2/sopds-go_1.3.2_linux_arm64.tar.gz"
      sha256 "a052c4e8a931b782ab2aaac8672c8252a4ca251e1e17db1d82e5d6ba1cdd44d4"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  def caveats
    <<~EOS
      sopds-go is now installed. To complete setup:

        1. Start PostgreSQL: brew services start postgresql@18
        2. Initialize the database:
             psql -U postgres -f #{pkgshare}/init.sql
        3. Create config: sopds init
        4. Edit config.yaml.example as a starting template:
             cat #{pkgshare}/config.yaml.example
        5. Run migrations: sopds migrate
        6. Start: sopds start

      Optional runtime deps (install separately):
        - calibre        — for FB2 → MOBI conversion (`brew install calibre`)
        - espeak-ng      — for IPA-based Piper TTS voices (`brew install espeak-ng`)

      For CUDA-accelerated TTS (NVIDIA GPU only), see sopds-tts-rs/ in the
      upstream repo: https://github.com/dimgord/sopds-go/tree/main/sopds-tts-rs
    EOS
  end

  test do
    system "#{bin}/sopds", "version"
  end
end
