# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SopdsGo < Formula
  desc "Self-hosted OPDS catalog server (Go rewrite of SOPDS)"
  homepage "https://github.com/dimgord/sopds-go"
  version "1.3.0"
  license "AGPL-3.0"

  depends_on "postgresql@16" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.0/sopds-go_1.3.0_macos_x86_64.tar.gz"
      sha256 "8c33ff18b91eaf0d284433602ba5196ffd288fb7d863c0a32a49e253e17adc26"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.0/sopds-go_1.3.0_macos_arm64.tar.gz"
      sha256 "c436644cb3ffb16239a2f0df5c1171bd13cedb565bfe1354cc8ec5dc39d0cae6"

      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.0/sopds-go_1.3.0_linux_x86_64.tar.gz"
      sha256 "b9cb5c100e651d7425fbe8f3159742683830b9249722598e3b0b0f3279fcae58"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dimgord/sopds-go/releases/download/v1.3.0/sopds-go_1.3.0_linux_arm64.tar.gz"
      sha256 "09653cf1d434420732e9074437039a7590f20bd57dd4c0f78f65bf279a5205e1"
      define_method(:install) do
        bin.install "sopds"
        bin.install "zipdupes"
        pkgshare.install "config.yaml.example"
        pkgshare.install "init.sql"
      end
    end
  end

  def caveats
    <<~EOS
      sopds-go is now installed. To complete setup:

        1. Start PostgreSQL: brew services start postgresql@16
        2. Initialize the database:
             psql -U postgres -f #{pkgshare}/init.sql
        3. Create config: sopds init
        4. Edit config.yaml.example as a starting template:
             cat #{pkgshare}/config.yaml.example
        5. Run migrations: sopds migrate
        6. Start: sopds start

      Optional runtime deps (install separately):
        - calibre        — for FB2 → MOBI conversion (`brew install calibre`)
        - espeak-ng      — for IPA-based Piper TTS voices (`brew install espeak-ng`)

      For CUDA-accelerated TTS (NVIDIA GPU only), see sopds-tts-rs/ in the
      upstream repo: https://github.com/dimgord/sopds-go/tree/main/sopds-tts-rs
    EOS
  end

  test do
    system "#{bin}/sopds", "version"
  end
end
